{% set name = "pytest-randomly" %}
{% set version = "3.13.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 079c78b94693189879fbd7304de4e147304f0811fa96249ea5619f2f1cd33df0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - importlib-metadata >=3.6.0
    - pytest 

test:
  imports:
    - pytest_randomly
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytest-dev/pytest-randomly
  summary: Pytest plugin to randomly order tests and control random.seed
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cpcloud
