{% set name = "pytest-randomly" %}
{% set version = "4.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 521c216e94e8b40cccfa5da5e403e9c45a3071db6f9f1cb2d5658e9017def2a9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - importlib-metadata >=3.6
    - pytest 

test:
  imports:
    - pytest_randomly
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytest-dev/pytest-randomly
  summary: Pytest plugin to randomly order tests and control random.seed
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cpcloud
