{% set name = "pytest-randomly" %}
{% set version = "5.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e9c575a5873ef168ddbe340ed9e97ce9edb4492ccc821e4b2ac6bb1f0ed515d2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=77
  run:
    - python >={{ python_min }}
    - pytest >=8

test:
  imports:
    - pytest_randomly
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pytest-dev/pytest-randomly
  summary: Pytest plugin to randomly order tests and control random.seed
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cpcloud
    - soapy1
